site_name: My Docs

theme: 
    name: material

    icon:
    admonition:
      <type>: <icon> 

    # Code copy button
    features:
      - content.code.copy

    # Code selection button
    features:
      - content.code.select

    # Code annotations
    features:
      - content.code.annotate

    features:
      - navigation.tabs
      - navigation.instant
      - navigation.expand

    features:
      - content.code.annotate


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  # Code blocks configure
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  # Content tabs
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 

  # Data tables
  - tables

  # Icons, Emojis
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

  # Diagrams
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Home: index.md
  - Documentation: 
    - Software: 
      - "Thread API": Documentation/Software/thread.md
  - Faq:
    - Why Study Computer Systems Fundamentals?: Faq/why-study-computer-systems.md